sudo: false

language: bash

addons:

        apt:

                sources:

                        - sourceline:'ppa:duggan/bats'

                packages:

                        - bats

                        - bc

script: bats ./19745146_kadai3TEST.sh
